version: "3"

services:
  banco_de_dados:
    container_name: postgres15
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=base_dev
    ports:
      - 5432:5432
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
      # - pgdata:/var/lib/postgresql/data
      - ./data:/postgres/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  pgdata: